[app]
storage_dir = "storage"
max_upload_mb = 200
max_storage_mb = 1000
pbkdf2_iterations = 600000
session_hours = 8
secret_key_env = "FLASK_SECRET_KEY"
secure_cookies = 1
encrypt_metadata = 1
totp_valid_window = 2
